CREATE OR REPLACE PROCEDURE 
incluir_segmercado(p_ID IN SEGMERCADO.ID%TYPE, p_DESCRICAO IN SEGMERCADO.DESCRICAO%TYPE)
IS
BEGIN
	INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, UPPER(p_DESCRICAO));
	COMMIT;
END;