DECLARE
  v_COD produto_exercicio.cod%type;
BEGIN
   v_COD := '41232';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
    v_COD := '32223';
   UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(DESCRICAO,'-','>') WHERE COD = v_COD;
   COMMIT;
END;
