SET SERVEROUTPUT ON;

DECLARE
    v_ID SEGMERCADO.ID%type := 3;
    v_IDSaida SEGMERCADO.ID%type;
    v_DESCRICAO SEGMERCADO.DESCRICAO%type;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
    SELECT ID INTO v_IDSaida FROM SEGMERCADO WHERE ID = v_ID;
    dbms_output.put_line(v_DESCRICAO);
    dbms_output.put_line(v_IDSaida);
END;